/*
*	Sonic 3 A.I.R. PS3 port -- the Cg versions of the .shader files, embedded in the executable.
*
*	Same idea as RSDKv4-PS3 (crt_shaders.h): no dependency on the file system / data packages.
*	Generated from shader_cg/*.shader -- if you edit a .shader, regenerate this header
*	(or edit the string here directly).
*
*	Use:  const char* text = getEmbeddedCgShaderText(L"data/shader/simple_rect_textured.shader");
*	      -> returns the full .shader text (sections "## Vertex" / "## Fragment" / "## TECH") or nullptr
*/

#pragma once

#include <string.h>
#include <wchar.h>

static const char* s3air_cg_file_render_plane =
"\n"
"## ----- Shared -------------------------------------------------------------------\n"
"\n"
"// Cg version (PS3): port of the GL_ES / non-buffer-texture path (no isamplerBuffer, no bit operations, no integer math)\n"
"//  - integer uniforms (ActiveRect, GameResolution, PlayfieldSize, PriorityFlag, ScrollOffsetX/Y, VScrollOffsetBias) are float uniforms here,\n"
"//    the PS3 Shader class converts int / Vec2i / Vec4i / Recti to float\n"
"//  - all \"integers\" are floats holding integer values; divisions use floor((v + 0.5) / d) so that results do not depend on the\n"
"//    precision of the reciprocal (a plain floor(v / d) can be off by one at exact multiples)\n"
"\n"
"// 16-bit values (plane patterns, scroll offsets) are uploaded as LUMINANCE_ALPHA bytes in host memory order.\n"
"// PS3 is big endian: the high byte comes first -> luminance = high byte, alpha = low byte; the result is (low, high).\n"
"// If the data turns out to already be little endian, change this to \".ra\"\n"
"#define TEXEL16(t) ((t).ar)\n"
"\n"
"\n"
"## ----- Vertex -------------------------------------------------------------------\n"
"\n"
"uniform float4 ActiveRect;\n"
"uniform float2 GameResolution;\n"
"\n"
"void vmain(float2 position : POSITION,\n"
"           out float4 oPos : POSITION,\n"
"           out float2 LocalOffset : TEXCOORD0)\n"
"{\n"
"\tfloat2 screenPosition;\n"
"\tscreenPosition.x = ActiveRect.x + floor(position.x * ActiveRect.z + 0.5);\n"
"\tscreenPosition.y = ActiveRect.y + floor(position.y * ActiveRect.w + 0.5);\n"
"\n"
"\tLocalOffset = screenPosition;\n"
"\n"
"\toPos.x = screenPosition.x / GameResolution.x * 2.0 - 1.0;\n"
"\toPos.y = screenPosition.y / GameResolution.y * 2.0 - 1.0;\n"
"\toPos.z = 0.5;\t// Has an effect only if depth write is enabled (it is for the priority plane, i.e. when PriorityFlag == 1)\n"
"\toPos.w = 1.0;\n"
"}\n"
"\n"
"\n"
"## ----- Fragment -----------------------------------------------------------------\n"
"\n"
"uniform sampler2D IndexTexture;\n"
"uniform sampler2D PatternCacheTexture;\n"
"uniform sampler2D PaletteTexture;\n"
"uniform float PaletteOffset;\n"
"uniform float4 PlayfieldSize;\n"
"uniform float PriorityFlag;\t\t// 0 or 1\n"
"\n"
"#ifdef HORIZONTAL_SCROLLING\n"
"\tuniform sampler2D HScrollOffsetsTexture;\n"
"#else\n"
"\tuniform float ScrollOffsetX;\n"
"#endif\n"
"\n"
"#ifdef VERTICAL_SCROLLING\n"
"\tuniform sampler2D VScrollOffsetsTexture;\n"
"\tuniform float VScrollOffsetBias;\n"
"#else\n"
"\tuniform float ScrollOffsetY;\n"
"#endif\n"
"\n"
"\n"
"// Integer division and modulo on floats holding integer values (d > 0)\n"
"float idiv(float v, float d)\n"
"{\n"
"\treturn floor((v + 0.5) / d);\n"
"}\n"
"\n"
"float imod(float v, float d)\n"
"{\n"
"\treturn v - floor((v + 0.5) / d) * d;\n"
"}\n"
"\n"
"float4 getPaletteColor(float paletteIndex, float paletteOffsetY)\n"
"{\n"
"\tfloat paletteY = idiv(paletteIndex, 256.0);\n"
"\tfloat paletteX = paletteIndex - paletteY * 256.0;\n"
"\tfloat2 samplePosition = float2((paletteX + 0.5) / 256.0, (paletteY + 0.5) / 4.0 + paletteOffsetY);\n"
"\treturn tex2D(PaletteTexture, samplePosition);\n"
"}\n"
"\n"
"\n"
"float4 fmain(float2 LocalOffset : TEXCOORD0) : COLOR\n"
"{\n"
"\tfloat ix = floor(LocalOffset.x);\n"
"\tfloat iy = floor(LocalOffset.y);\n"
"\n"
"#ifdef HORIZONTAL_SCROLLING\n"
"\tfloat2 texelScrollX = TEXEL16(tex2D(HScrollOffsetsTexture, float2((iy + 0.5) / 256.0, 0.5)));\n"
"\tfloat scrollOffsetLookupXH = imod(floor(texelScrollX.y * 255.0 + 0.5), 16.0);\n"
"\tfloat scrollOffsetLookupXL = floor(texelScrollX.x * 255.0 + 0.5);\n"
"\tfloat scrollOffsetLookupX = scrollOffsetLookupXL + scrollOffsetLookupXH * 256.0;\n"
"#else\n"
"\tfloat scrollOffsetLookupX = ScrollOffsetX;\n"
"#endif\n"
"\n"
"#ifdef VERTICAL_SCROLLING\n"
"\tfloat vx = ix - VScrollOffsetBias;\n"
"\tvx = idiv(imod(vx, 512.0), 16.0);\n"
"\tfloat2 texelScrollY = TEXEL16(tex2D(VScrollOffsetsTexture, float2((vx + 0.5) / 32.0, 0.5)));\n"
"\tfloat scrollOffsetLookupYH = imod(floor(texelScrollY.y * 255.0 + 0.5), 16.0);\n"
"\tfloat scrollOffsetLookupYL = floor(texelScrollY.x * 255.0 + 0.5);\n"
"\tfloat scrollOffsetLookupY = scrollOffsetLookupYL + scrollOffsetLookupYH * 256.0;\n"
"#else\n"
"\tfloat scrollOffsetLookupY = ScrollOffsetY;\n"
"#endif\n"
"\n"
"\tix += scrollOffsetLookupX;\n"
"\tiy += scrollOffsetLookupY;\n"
"\tix = imod(ix, 4096.0);\n"
"\tiy = imod(iy, PlayfieldSize.y);\n"
"\n"
"#ifdef NOREPEAT_SCROLLOFFSETS\n"
"\tif (ix >= PlayfieldSize.x)\n"
"\t\tdiscard;\n"
"#else\n"
"\tix = imod(ix, PlayfieldSize.x);\n"
"#endif\n"
"\n"
"\tfloat patternX = idiv(ix, 8.0);\n"
"\tfloat patternY = idiv(iy, 8.0);\n"
"\tfloat localX = ix - patternX * 8.0;\n"
"\tfloat localY = iy - patternY * 8.0;\n"
"\n"
"\tfloat2 texel = TEXEL16(tex2D(IndexTexture, float2((patternX + patternY * PlayfieldSize.z + 0.5) / (PlayfieldSize.z * PlayfieldSize.w), 0.5)));\n"
"\tfloat patternIndexH = floor(texel.y * 255.0 + 0.5);\n"
"\tfloat patternIndexL = floor(texel.x * 255.0 + 0.5);\n"
"\n"
"\tbool isHighPriority = (patternIndexH >= 128.0);\n"
"\tbool wantsHighPriority = (PriorityFlag >= 0.5);\n"
"\tif (isHighPriority != wantsHighPriority)\n"
"\t\tdiscard;\n"
"\n"
"\tfloat atex = idiv(imod(patternIndexH, 128.0), 32.0) * 16.0;\n"
"\tlocalX = (imod(patternIndexH, 16.0) < 8.0) ? localX : (7.0 - localX);\n"
"\tlocalY = (imod(patternIndexH, 32.0) < 16.0) ? localY : (7.0 - localY);\n"
"\n"
"\tfloat patternCacheLookupIndexX = localX + localY * 8.0;\n"
"\tfloat patternCacheLookupIndexY = patternIndexL + imod(patternIndexH, 8.0) * 256.0;\n"
"\tfloat paletteIndex = floor(tex2D(PatternCacheTexture, float2((patternCacheLookupIndexX + 0.5) / 64.0, (patternCacheLookupIndexY + 0.5) / 2048.0)).x * 255.0 + 0.5);\n"
"\tpaletteIndex += atex;\n"
"\n"
"\tfloat4 color = getPaletteColor(paletteIndex, PaletteOffset);\n"
"#ifdef ALPHA_TEST\n"
"\tif (color.a < 0.01)\n"
"\t\tdiscard;\n"
"#endif\n"
"\n"
"\treturn color;\n"
"}\n"
"\n"
"\n"
"## ----- TECH ---------------------------------------------------------------------\n"
"\n"
"technique Standard\n"
"{\n"
"\tblendfunc = opaque;\n"
"\tvs = Shared + Vertex;\n"
"\tfs = Shared + Fragment;\n"
"\tvertexattrib[0] = position;\n"
"}\n"
"\n"
"technique HorizontalScrolling : Standard\n"
"{\n"
"\tdefine = HORIZONTAL_SCROLLING;\n"
"}\n"
"\n"
"technique HorizontalScrollingNoRepeat : Standard\n"
"{\n"
"\tdefine = HORIZONTAL_SCROLLING;\n"
"\tdefine = NOREPEAT_SCROLLOFFSETS;\n"
"}\n"
"\n"
"technique VerticalScrolling : Standard\n"
"{\n"
"\tdefine = VERTICAL_SCROLLING;\n"
"}\n"
"\n"
"technique HorizontalVerticalScrolling : Standard\n"
"{\n"
"\tdefine = HORIZONTAL_SCROLLING;\n"
"\tdefine = VERTICAL_SCROLLING;\n"
"}\n"
;

static const char* s3air_cg_file_render_sprite_component =
"\n"
"## ----- Shared -------------------------------------------------------------------\n"
"\n"
"// Cg version (PS3). Integer uniforms (Size, Position, PivotOffset, GameResolution) are float uniforms here\n"
"\n"
"uniform float2 Size;\n"
"\n"
"\n"
"## ----- Vertex -------------------------------------------------------------------\n"
"\n"
"uniform float3 Position;\t\t// With z = priority flag (0 or 1)\n"
"uniform float2 PivotOffset;\n"
"uniform float4 Transformation;\n"
"uniform float2 GameResolution;\n"
"\n"
"void vmain(float2 position : POSITION,\n"
"           out float4 oPos : POSITION,\n"
"           out float2 uv0 : TEXCOORD0)\n"
"{\n"
"\t// Calculate local offset\n"
"\tfloat2 LocalOffset;\n"
"\tLocalOffset.x = position.x * Size.x;\n"
"\tLocalOffset.y = position.y * Size.y;\n"
"\n"
"\t// Transform\n"
"\tfloat2 v = LocalOffset.xy + PivotOffset.xy;\n"
"\tfloat2 transformedVertex;\n"
"\ttransformedVertex.x = v.x * Transformation.x + v.y * Transformation.y;\n"
"\ttransformedVertex.y = v.x * Transformation.z + v.y * Transformation.w;\n"
"\n"
"\t// Transform local -> screen space\n"
"\ttransformedVertex.x = Position.x + transformedVertex.x;\n"
"\ttransformedVertex.y = Position.y + transformedVertex.y;\n"
"\n"
"\t// Transform screen space -> view space\n"
"\toPos.x = transformedVertex.x / GameResolution.x * 2.0 - 1.0;\n"
"\toPos.y = transformedVertex.y / GameResolution.y * 2.0 - 1.0;\n"
"\toPos.z = Position.z * 0.5;\n"
"\toPos.w = 1.0;\n"
"\n"
"\tuv0 = position.xy;\n"
"}\n"
"\n"
"\n"
"## ----- Fragment -----------------------------------------------------------------\n"
"\n"
"uniform sampler2D SpriteTexture;\n"
"uniform float4 TintColor;\n"
"uniform float4 AddedColor;\n"
"\n"
"float4 fmain(float2 uv0 : TEXCOORD0) : COLOR\n"
"{\n"
"\tfloat4 color = tex2D(SpriteTexture, uv0.xy);\n"
"\tcolor = float4(AddedColor.rgb, 0.0) + color * TintColor;\n"
"#ifdef ALPHA_TEST\n"
"\tif (color.a < 0.01)\n"
"\t\tdiscard;\n"
"#endif\n"
"\n"
"\treturn color;\n"
"}\n"
"\n"
"\n"
"## ----- TECH ---------------------------------------------------------------------\n"
"\n"
"technique Standard\n"
"{\n"
"\tblendfunc = alpha;\n"
"\tvs = Shared + Vertex;\n"
"\tfs = Shared + Fragment;\n"
"\tvertexattrib[0] = position;\n"
"}\n"
"\n"
"technique Standard_AlphaTest : Standard\n"
"{\n"
"\tdefine = ALPHA_TEST;\n"
"}\n"
;

static const char* s3air_cg_file_render_sprite_palette =
"\n"
"## ----- Shared -------------------------------------------------------------------\n"
"\n"
"// Cg version (PS3): port of the GL_ES / non-buffer-texture path (no isamplerBuffer, no integer math)\n"
"// Integer uniforms (Size, Position, PivotOffset, GameResolution, WaterLevel, Atex) are float uniforms here\n"
"\n"
"uniform float2 Size;\n"
"\n"
"\n"
"## ----- Vertex -------------------------------------------------------------------\n"
"\n"
"uniform float3 Position;\t\t// With z = priority flag (0 or 1)\n"
"uniform float2 PivotOffset;\n"
"uniform float4 Transformation;\n"
"uniform float2 GameResolution;\n"
"uniform float WaterLevel;\n"
"\n"
"void vmain(float2 position : POSITION,\n"
"           out float4 oPos : POSITION,\n"
"           out float3 LocalOffset : TEXCOORD0)\n"
"{\n"
"\t// Calculate local offset\n"
"\tLocalOffset.x = position.x * Size.x;\n"
"\tLocalOffset.y = position.y * Size.y;\n"
"\n"
"\t// Transform\n"
"\tfloat2 v = LocalOffset.xy + PivotOffset.xy;\n"
"\tfloat2 transformedVertex;\n"
"\ttransformedVertex.x = v.x * Transformation.x + v.y * Transformation.y;\n"
"\ttransformedVertex.y = v.x * Transformation.z + v.y * Transformation.w;\n"
"\n"
"\t// Transform local -> screen space\n"
"\ttransformedVertex.x = Position.x + transformedVertex.x;\n"
"\ttransformedVertex.y = Position.y + transformedVertex.y;\n"
"\n"
"\t// Transform screen space -> view space\n"
"\toPos.x = transformedVertex.x / GameResolution.x * 2.0 - 1.0;\n"
"\toPos.y = transformedVertex.y / GameResolution.y * 2.0 - 1.0;\n"
"\toPos.z = Position.z * 0.5;\n"
"\toPos.w = 1.0;\n"
"\n"
"\t// Calculate water offset\n"
"\tLocalOffset.z = transformedVertex.y - WaterLevel;\n"
"}\n"
"\n"
"\n"
"## ----- Fragment -----------------------------------------------------------------\n"
"\n"
"uniform sampler2D SpriteTexture;\t// 8-bit index texture (GL_LUMINANCE), NEAREST\n"
"uniform sampler2D PaletteTexture;\t// 256 x 4\n"
"uniform float Atex;\n"
"uniform float4 TintColor;\n"
"uniform float4 AddedColor;\n"
"\n"
"\n"
"float4 getPaletteColor(float paletteIndex, float paletteOffsetY)\n"
"{\n"
"\tfloat paletteY = floor((paletteIndex + 0.5) / 256.0);\n"
"\tfloat paletteX = paletteIndex - paletteY * 256.0;\n"
"\tfloat2 samplePosition = float2((paletteX + 0.5) / 256.0, (paletteY + 0.5) / 4.0 + paletteOffsetY);\n"
"\treturn tex2D(PaletteTexture, samplePosition);\n"
"}\n"
"\n"
"\n"
"float4 fmain(float3 LocalOffset : TEXCOORD0) : COLOR\n"
"{\n"
"\tfloat ix = floor(LocalOffset.x);\n"
"\tfloat iy = floor(LocalOffset.y);\n"
"\n"
"\t// 8-bit normalized -> index (rounding; \"* 256.0\" + truncation would turn 255 into 256)\n"
"\tfloat paletteIndex = Atex + floor(tex2D(SpriteTexture, float2((ix + 0.5) / Size.x, (iy + 0.5) / Size.y)).x * 255.0 + 0.5);\n"
"\n"
"\tfloat4 color = getPaletteColor(paletteIndex, clamp(LocalOffset.z, 0.0, 0.5));\n"
"\tcolor = float4(AddedColor.rgb, 0.0) + color * TintColor;\n"
"#ifdef ALPHA_TEST\n"
"\tif (color.a < 0.01)\n"
"\t\tdiscard;\n"
"#endif\n"
"\n"
"\treturn color;\n"
"}\n"
"\n"
"\n"
"## ----- TECH ---------------------------------------------------------------------\n"
"\n"
"technique Standard\n"
"{\n"
"\tblendfunc = alpha;\n"
"\tvs = Shared + Vertex;\n"
"\tfs = Shared + Fragment;\n"
"\tvertexattrib[0] = position;\n"
"}\n"
"\n"
"technique Standard_AlphaTest : Standard\n"
"{\n"
"\tdefine = ALPHA_TEST;\n"
"}\n"
;

static const char* s3air_cg_file_render_sprite_vdp =
"\n"
"## ----- Shared -------------------------------------------------------------------\n"
"\n"
"// Cg version (PS3): port of the GL_ES / non-buffer-texture path (no isamplerBuffer, no bit operations, no integer math)\n"
"// Integer uniforms (Size, FirstPattern, Position, GameResolution, WaterLevel) are float uniforms here;\n"
"// \"integers\" are floats holding integer values, divisions use floor((v + 0.5) / d) so they do not depend on the precision of the reciprocal\n"
"\n"
"uniform float2 Size;\n"
"uniform float FirstPattern;\n"
"\n"
"\n"
"## ----- Vertex -------------------------------------------------------------------\n"
"\n"
"uniform float3 Position;\t\t// With z = priority flag (0 or 1)\n"
"uniform float2 GameResolution;\n"
"uniform float WaterLevel;\n"
"\n"
"float imod(float v, float d)\n"
"{\n"
"\treturn v - floor((v + 0.5) / d) * d;\n"
"}\n"
"\n"
"void vmain(float2 position : POSITION,\n"
"           out float4 oPos : POSITION,\n"
"           out float3 LocalOffset : TEXCOORD0)\n"
"{\n"
"\t// Calculate local offset\n"
"\tLocalOffset.x = position.x * (Size.x * 8.0);\n"
"\tLocalOffset.y = position.y * (Size.y * 8.0);\n"
"\n"
"\t// Flip if necessary\n"
"\tfloat2 transformedVertex = position.xy;\n"
"\tif (imod(FirstPattern, 4096.0) >= 2048.0)\n"
"\t\ttransformedVertex.x = (1.0 - transformedVertex.x);\n"
"\tif (imod(FirstPattern, 8192.0) >= 4096.0)\n"
"\t\ttransformedVertex.y = (1.0 - transformedVertex.y);\n"
"\n"
"\t// Transform local -> screen space\n"
"\ttransformedVertex.x = Position.x + transformedVertex.x * (Size.x * 8.0);\n"
"\ttransformedVertex.y = Position.y + transformedVertex.y * (Size.y * 8.0);\n"
"\n"
"\t// Transform screen space -> view space\n"
"\toPos.x = transformedVertex.x / GameResolution.x * 2.0 - 1.0;\n"
"\toPos.y = transformedVertex.y / GameResolution.y * 2.0 - 1.0;\n"
"\toPos.z = Position.z * 0.5;\n"
"\toPos.w = 1.0;\n"
"\n"
"\t// Calculate water offset\n"
"\tLocalOffset.z = transformedVertex.y - WaterLevel;\n"
"}\n"
"\n"
"\n"
"## ----- Fragment -----------------------------------------------------------------\n"
"\n"
"uniform sampler2D PatternCacheTexture;\n"
"uniform sampler2D PaletteTexture;\n"
"uniform float4 TintColor;\n"
"uniform float4 AddedColor;\n"
"\n"
"\n"
"float idiv(float v, float d)\n"
"{\n"
"\treturn floor((v + 0.5) / d);\n"
"}\n"
"\n"
"float imod(float v, float d)\n"
"{\n"
"\treturn v - floor((v + 0.5) / d) * d;\n"
"}\n"
"\n"
"float4 getPaletteColor(float paletteIndex, float paletteOffsetY)\n"
"{\n"
"\tfloat paletteY = idiv(paletteIndex, 256.0);\n"
"\tfloat paletteX = paletteIndex - paletteY * 256.0;\n"
"\tfloat2 samplePosition = float2((paletteX + 0.5) / 256.0, (paletteY + 0.5) / 4.0 + paletteOffsetY);\n"
"\treturn tex2D(PaletteTexture, samplePosition);\n"
"}\n"
"\n"
"\n"
"float4 fmain(float3 LocalOffset : TEXCOORD0) : COLOR\n"
"{\n"
"\tfloat ix = floor(LocalOffset.x);\n"
"\tfloat iy = floor(LocalOffset.y);\n"
"\tfloat patternX = idiv(ix, 8.0);\n"
"\tfloat patternY = idiv(iy, 8.0);\n"
"\tfloat localX = ix - patternX * 8.0;\n"
"\tfloat localY = iy - patternY * 8.0;\n"
"\n"
"\tfloat patternIndex = FirstPattern + patternX * Size.y + patternY;\n"
"\tfloat atex = idiv(imod(patternIndex, 32768.0), 8192.0) * 16.0;\n"
"\n"
"\tfloat patternCacheLookupIndexX = localX + localY * 8.0;\n"
"\tfloat patternCacheLookupIndexY = imod(patternIndex, 2048.0);\n"
"\tfloat paletteIndex = floor(tex2D(PatternCacheTexture, float2((patternCacheLookupIndexX + 0.5) / 64.0, (patternCacheLookupIndexY + 0.5) / 2048.0)).x * 255.0 + 0.5);\n"
"\tpaletteIndex += atex;\n"
"\n"
"\tfloat4 color = getPaletteColor(paletteIndex, clamp(LocalOffset.z, 0.0, 0.5));\n"
"\tcolor = float4(AddedColor.rgb, 0.0) + color * TintColor;\n"
"\tif (color.a < 0.01)\n"
"\t\tdiscard;\n"
"\n"
"\treturn color;\n"
"}\n"
"\n"
"\n"
"## ----- TECH ---------------------------------------------------------------------\n"
"\n"
"technique Standard\n"
"{\n"
"\tblendfunc = alpha;\n"
"\tvs = Shared + Vertex;\n"
"\tfs = Shared + Fragment;\n"
"\tvertexattrib[0] = position;\n"
"}\n"
;

static const char* s3air_cg_file_simple_copy_screen =
"\n"
"## ----- Shared -------------------------------------------------------------------\n"
"\n"
"// Cg version (PS3). Entry points: vmain / fmain\n"
"\n"
"\n"
"## ----- Vertex -------------------------------------------------------------------\n"
"\n"
"void vmain(float2 position : POSITION,\n"
"           out float4 oPos : POSITION,\n"
"           out float2 uv0  : TEXCOORD0)\n"
"{\n"
"\tuv0 = position;\n"
"\toPos = float4(position.x * 2.0 - 1.0, position.y * 2.0 - 1.0, 0.0, 1.0);\n"
"}\n"
"\n"
"\n"
"## ----- Fragment -----------------------------------------------------------------\n"
"\n"
"uniform sampler2D MainTexture;\n"
"\n"
"float4 fmain(float2 uv0 : TEXCOORD0) : COLOR\n"
"{\n"
"\treturn tex2D(MainTexture, uv0);\n"
"}\n"
"\n"
"\n"
"## ----- TECH ---------------------------------------------------------------------\n"
"\n"
"technique Standard\n"
"{\n"
"\tblendfunc = opaque;\n"
"\tvs = Shared + Vertex;\n"
"\tfs = Shared + Fragment;\n"
"\tvertexattrib[0] = position;\n"
"}\n"
;

static const char* s3air_cg_file_simple_rect_colored =
"\n"
"## ----- Shared -------------------------------------------------------------------\n"
"\n"
"// Cg version (PS3). Entry points: vmain / fmain\n"
"\n"
"\n"
"## ----- Vertex -------------------------------------------------------------------\n"
"\n"
"uniform float4 Transform;\n"
"\n"
"void vmain(float2 position : POSITION,\n"
"           out float4 oPos : POSITION)\n"
"{\n"
"\tfloat2 pos = float2(Transform.x + position.x * Transform.z, Transform.y + position.y * Transform.w);\n"
"\n"
"\t// Intentionally using a z-value of 0.5\n"
"\toPos = float4(pos, 0.5, 1.0);\n"
"}\n"
"\n"
"\n"
"## ----- Fragment -----------------------------------------------------------------\n"
"\n"
"uniform float4 Color;\n"
"\n"
"float4 fmain() : COLOR\n"
"{\n"
"\treturn Color;\n"
"}\n"
"\n"
"\n"
"## ----- TECH ---------------------------------------------------------------------\n"
"\n"
"technique Standard\n"
"{\n"
"\tblendfunc = alpha;\n"
"\tvs = Shared + Vertex;\n"
"\tfs = Shared + Fragment;\n"
"\tvertexattrib[0] = position;\n"
"}\n"
;

static const char* s3air_cg_file_simple_rect_indexed =
"\n"
"## ----- Shared -------------------------------------------------------------------\n"
"\n"
"// Cg version (PS3): port of the GL_ES / non-buffer-texture path (no isamplerBuffer, no bit operations)\n"
"// The wrapper passes Size as Vec2i; the PS3 Shader class converts int uniforms to float\n"
"\n"
"uniform float2 Size;\n"
"\n"
"\n"
"## ----- Vertex -------------------------------------------------------------------\n"
"\n"
"uniform float4 Transform;\n"
"\n"
"void vmain(float2 position : POSITION,\n"
"           out float4 oPos : POSITION,\n"
"           out float2 LocalOffset : TEXCOORD0)\n"
"{\n"
"\t// Calculate local offset\n"
"\tLocalOffset = position * Size;\n"
"\n"
"\tfloat2 pos = float2(Transform.x + position.x * Transform.z, Transform.y + position.y * Transform.w);\n"
"\toPos = float4(pos, 0.0, 1.0);\n"
"}\n"
"\n"
"\n"
"## ----- Fragment -----------------------------------------------------------------\n"
"\n"
"uniform sampler2D MainTexture;\t\t// 8-bit index texture (GL_LUMINANCE), NEAREST\n"
"uniform sampler2D PaletteTexture;\t// 256 x 4\n"
"#ifdef USE_TINT_COLOR\n"
"\tuniform float4 TintColor;\n"
"\tuniform float4 AddedColor;\n"
"#endif\n"
"\n"
"float4 getPaletteColor(float paletteIndex, float paletteOffsetY)\n"
"{\n"
"\tfloat paletteY = floor(paletteIndex / 256.0);\n"
"\tfloat paletteX = paletteIndex - paletteY * 256.0;\n"
"\tfloat2 samplePosition = float2((paletteX + 0.5) / 256.0, (paletteY + 0.5) / 4.0 + paletteOffsetY);\n"
"\treturn tex2D(PaletteTexture, samplePosition);\n"
"}\n"
"\n"
"float4 fmain(float2 LocalOffset : TEXCOORD0) : COLOR\n"
"{\n"
"\tfloat ix = floor(LocalOffset.x);\n"
"\tfloat iy = floor(LocalOffset.y);\n"
"\n"
"\t// 8-bit normalized -> index (rounding; \"* 256.0\" + truncation would turn 255 into 256)\n"
"\tfloat paletteIndex = floor(tex2D(MainTexture, float2((ix + 0.5) / Size.x, (iy + 0.5) / Size.y)).x * 255.0 + 0.5);\n"
"\n"
"\tfloat4 color = getPaletteColor(paletteIndex, 0.0);\n"
"#ifdef USE_TINT_COLOR\n"
"\tcolor = float4(AddedColor.rgb, 0.0) + color * TintColor;\n"
"#endif\n"
"#ifdef ALPHA_TEST\n"
"\tif (color.a < 0.01)\n"
"\t\tdiscard;\n"
"#endif\n"
"\treturn color;\n"
"}\n"
"\n"
"\n"
"## ----- TECH ---------------------------------------------------------------------\n"
"\n"
"technique Standard\n"
"{\n"
"\tblendfunc = alpha;\n"
"\tvs = Shared + Vertex;\n"
"\tfs = Shared + Fragment;\n"
"\tvertexattrib[0] = position;\n"
"}\n"
"\n"
"technique TintColor : Standard\n"
"{\n"
"\tdefine = USE_TINT_COLOR;\n"
"}\n"
"\n"
"technique Standard_AlphaTest : Standard\n"
"{\n"
"\tdefine = ALPHA_TEST;\n"
"}\n"
"\n"
"technique TintColor_AlphaTest : Standard\n"
"{\n"
"\tdefine = ALPHA_TEST;\n"
"\tdefine = USE_TINT_COLOR;\n"
"}\n"
;

static const char* s3air_cg_file_simple_rect_textured =
"\n"
"## ----- Shared -------------------------------------------------------------------\n"
"\n"
"// Cg version (PS3). Entry points: vmain / fmain\n"
"\n"
"\n"
"## ----- Vertex -------------------------------------------------------------------\n"
"\n"
"uniform float4 Transform;\n"
"\n"
"void vmain(float2 position : POSITION,\n"
"           out float4 oPos : POSITION,\n"
"           out float2 uv0  : TEXCOORD0)\n"
"{\n"
"\tuv0 = position;\n"
"\tfloat2 pos = float2(Transform.x + position.x * Transform.z, Transform.y + position.y * Transform.w);\n"
"\toPos = float4(pos, 0.0, 1.0);\n"
"}\n"
"\n"
"\n"
"## ----- Fragment -----------------------------------------------------------------\n"
"\n"
"uniform sampler2D MainTexture;\n"
"#ifdef USE_TINT_COLOR\n"
"\tuniform float4 TintColor;\n"
"\tuniform float4 AddedColor;\n"
"#endif\n"
"\n"
"float4 fmain(float2 uv0 : TEXCOORD0) : COLOR\n"
"{\n"
"\tfloat4 color = tex2D(MainTexture, uv0);\n"
"#ifdef USE_TINT_COLOR\n"
"\tcolor = float4(AddedColor.rgb, 0.0) + color * TintColor;\n"
"#endif\n"
"#ifdef ALPHA_TEST\n"
"\tif (color.a < 0.01)\n"
"\t\tdiscard;\n"
"#endif\n"
"\treturn color;\n"
"}\n"
"\n"
"\n"
"## ----- TECH ---------------------------------------------------------------------\n"
"\n"
"technique Standard\n"
"{\n"
"\tvs = Shared + Vertex;\n"
"\tfs = Shared + Fragment;\n"
"\tvertexattrib[0] = position;\n"
"}\n"
"\n"
"technique TintColor : Standard\n"
"{\n"
"\tdefine = USE_TINT_COLOR;\n"
"}\n"
"\n"
"technique Standard_AlphaTest : Standard\n"
"{\n"
"\tdefine = ALPHA_TEST;\n"
"}\n"
"\n"
"technique TintColor_AlphaTest : Standard\n"
"{\n"
"\tdefine = ALPHA_TEST;\n"
"\tdefine = USE_TINT_COLOR;\n"
"}\n"
;

static const char* s3air_cg_file_simple_rect_textured_uv =
"\n"
"## ----- Shared -------------------------------------------------------------------\n"
"\n"
"// Cg version (PS3). Entry points: vmain / fmain\n"
"\n"
"\n"
"## ----- Vertex -------------------------------------------------------------------\n"
"\n"
"uniform float4 Transform;\n"
"\n"
"void vmain(float2 position   : POSITION,\n"
"           float2 texcoords0 : TEXCOORD0,\n"
"           out float4 oPos : POSITION,\n"
"           out float2 uv0  : TEXCOORD0)\n"
"{\n"
"\tuv0 = texcoords0;\n"
"\tfloat2 pos = float2(Transform.x + position.x * Transform.z, Transform.y + position.y * Transform.w);\n"
"\toPos = float4(pos, 0.0, 1.0);\n"
"}\n"
"\n"
"\n"
"## ----- Fragment -----------------------------------------------------------------\n"
"\n"
"uniform sampler2D MainTexture;\n"
"#ifdef USE_TINT_COLOR\n"
"\tuniform float4 TintColor;\n"
"#endif\n"
"\n"
"float4 fmain(float2 uv0 : TEXCOORD0) : COLOR\n"
"{\n"
"\tfloat4 color = tex2D(MainTexture, uv0);\n"
"#ifdef USE_TINT_COLOR\n"
"\tcolor *= TintColor;\n"
"#endif\n"
"#ifdef ALPHA_TEST\n"
"\tif (color.a < 0.01)\n"
"\t\tdiscard;\n"
"#endif\n"
"\treturn color;\n"
"}\n"
"\n"
"\n"
"## ----- TECH ---------------------------------------------------------------------\n"
"\n"
"technique Standard\n"
"{\n"
"\tblendfunc = alpha;\n"
"\tvs = Shared + Vertex;\n"
"\tfs = Shared + Fragment;\n"
"\tvertexattrib[0] = position;\n"
"\tvertexattrib[1] = texcoords0;\n"
"}\n"
"\n"
"technique TintColor : Standard\n"
"{\n"
"\tdefine = USE_TINT_COLOR;\n"
"}\n"
"\n"
"technique Standard_AlphaTest : Standard\n"
"{\n"
"\tdefine = ALPHA_TEST;\n"
"}\n"
"\n"
"technique TintColor_AlphaTest : Standard\n"
"{\n"
"\tdefine = ALPHA_TEST;\n"
"\tdefine = USE_TINT_COLOR;\n"
"}\n"
;

static const char* s3air_cg_file_simple_rect_vertexcolor =
"\n"
"## ----- Shared -------------------------------------------------------------------\n"
"\n"
"// Cg version (PS3). Entry points: vmain / fmain\n"
"\n"
"\n"
"## ----- Vertex -------------------------------------------------------------------\n"
"\n"
"uniform float4 Transform;\n"
"\n"
"void vmain(float2 position : POSITION,\n"
"           float4 color    : COLOR0,\n"
"           out float4 oPos   : POSITION,\n"
"           out float4 interpolatedColor : TEXCOORD1)\n"
"{\n"
"\tfloat2 pos = float2(Transform.x + position.x * Transform.z, Transform.y + position.y * Transform.w);\n"
"\n"
"\t// Intentionally using a z-value of 0.5\n"
"\toPos = float4(pos, 0.5, 1.0);\n"
"\n"
"\t// Color goes through a TEXCOORD varying (COLOR interpolants get clamped)\n"
"\tinterpolatedColor = color;\n"
"}\n"
"\n"
"\n"
"## ----- Fragment -----------------------------------------------------------------\n"
"\n"
"float4 fmain(float4 interpolatedColor : TEXCOORD1) : COLOR\n"
"{\n"
"\treturn interpolatedColor;\n"
"}\n"
"\n"
"\n"
"## ----- TECH ---------------------------------------------------------------------\n"
"\n"
"technique Standard\n"
"{\n"
"\tblendfunc = alpha;\n"
"\tvs = Shared + Vertex;\n"
"\tfs = Shared + Fragment;\n"
"\tvertexattrib[0] = position;\n"
"}\n"
;

// Matches by file name only (the directory part of the path is ignored)
inline const char* getEmbeddedCgShaderText(const wchar_t* path)
{
	const wchar_t* name = path;
	for (const wchar_t* p = path; *p != 0; ++p)
	{
		if (*p == L'/' || *p == L'\\')
			name = p + 1;
	}

	if (wcscmp(name, L"render_plane.shader") == 0)
		return s3air_cg_file_render_plane;
	if (wcscmp(name, L"render_sprite_component.shader") == 0)
		return s3air_cg_file_render_sprite_component;
	if (wcscmp(name, L"render_sprite_palette.shader") == 0)
		return s3air_cg_file_render_sprite_palette;
	if (wcscmp(name, L"render_sprite_vdp.shader") == 0)
		return s3air_cg_file_render_sprite_vdp;
	if (wcscmp(name, L"simple_copy_screen.shader") == 0)
		return s3air_cg_file_simple_copy_screen;
	if (wcscmp(name, L"simple_rect_colored.shader") == 0)
		return s3air_cg_file_simple_rect_colored;
	if (wcscmp(name, L"simple_rect_indexed.shader") == 0)
		return s3air_cg_file_simple_rect_indexed;
	if (wcscmp(name, L"simple_rect_textured.shader") == 0)
		return s3air_cg_file_simple_rect_textured;
	if (wcscmp(name, L"simple_rect_textured_uv.shader") == 0)
		return s3air_cg_file_simple_rect_textured_uv;
	if (wcscmp(name, L"simple_rect_vertexcolor.shader") == 0)
		return s3air_cg_file_simple_rect_vertexcolor;

	return nullptr;
}
